# Generated by Django 2.1.1 on 2021-05-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20210511_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
