# Generated by Django 2.1.1 on 2021-05-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='name',
            field=models.CharField(blank=True, help_text='Nome da empresa', max_length=100, null=True),
        ),
    ]
