# Generated by Django 2.1.7 on 2021-05-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20210511_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='name',
            new_name='nome',
        ),
    ]
