# Generated by Django 2.1.1 on 2021-05-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='nome',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
