# Generated by Django 2.1.1 on 2021-05-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0002_registrohoraextra_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohoraextra',
            name='motivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
